import { addRole, deleteRole } from '../api/role.api';
import { getRole } from '../api/role.api';

export const APPLICATIONS = [
  {
    id: 1,
    status: 'Interview',
    image: 'https://logo.clearbit.com/apple.com',
    role: 'Full-Stack Developer',
    /*   role: getRole(['65e3086bae4519c854997e06']), */
    companyName: 'Apple, Inc.',
    date: '2024-02-27',
  },
  {
    id: 2,
    status: 'Applied',
    image: 'https://logo.clearbit.com/nintendo.com',
    role: 'Full-Stack Developer',
    companyName: 'Nintendo, Inc.',
    date: '2024-01-17',
  },
  {
    id: 3,
    status: 'Interview',
    image: 'https://logo.clearbit.com/nos.pt',
    role: 'Product Manager',
    companyName: 'NOS',
    date: '2024-02-22',
  },
  {
    id: 4,
    status: 'Wishlist',
    image: 'https://logo.clearbit.com/tesla.com',
    role: 'Product Manager',
    companyName: 'Tesla, Lda.',
    date: '2024-02-24',
  },
  {
    id: 5,
    status: 'Offer',
    image: 'https://logo.clearbit.com/microsoft.com',
    role: 'Full-Stack Developer',
    companyName: 'Microsoft, Inc.',
    date: '2024-01-13',
  },
  {
    id: 6,
    status: 'Rejected',
    image: 'https://logo.clearbit.com/google.com',
    role: 'Full-Stack Developer',
    companyName: 'Google, Inc.',
    date: '2024-02-12',
  },
  {
    id: 7,
    status: 'Interview',
    image: 'https://logo.clearbit.com/ironhack.com',
    role: 'Full-Stack Developer',
    companyName: 'Ironhack',
    date: '2024-02-10',
  },
  {
    id: 8,
    status: 'Wishlist',
    image: 'https://logo.clearbit.com/amazon.com',
    role: 'Software Engineer',
    companyName: 'Amazon, Inc.',
    date: '2024-03-05',
  },

  {
    id: 10,
    status: 'Interview',
    image: 'https://logo.clearbit.com/airbnb.com',
    role: 'Full-Stack Developer',
    companyName: 'Airbnb',
    date: '2024-02-20',
  },
  {
    id: 11,
    status: 'Wishlist',
    image: 'https://logo.clearbit.com/ibm.com',
    role: 'Full-Stack Developer',
    companyName: 'IBM, Inc.',
    date: '2024-03-01',
  },
  {
    id: 12,
    status: 'Applied',
    image: 'https://logo.clearbit.com/intel.com',
    role: 'Full-Stack Developer',
    companyName: 'Intel Corporation',
    date: '2024-02-29',
  },
  {
    id: 13,
    status: 'Interview',
    image: 'https://logo.clearbit.com/adobe.com',
    role: 'Full-Stack Developer',
    companyName: 'Adobe Inc.',
    date: '2024-02-28',
  },
  {
    id: 14,
    status: 'Wishlist',
    image: 'https://logo.clearbit.com/uber.com',
    role: 'Product Manager',
    companyName: 'Uber Technologies, Inc.',
    date: '2024-03-02',
  },
  {
    id: 15,
    status: 'Offer',
    image: 'https://logo.clearbit.com/samsung.com',
    role: 'Full-Stack Developer',
    companyName: 'Samsung Electronics',
    date: '2024-02-25',
  },
  {
    id: 16,
    status: 'Rejected',
    image: 'https://logo.clearbit.com/facebook.com',
    role: 'Full-Stack Developer',
    companyName: 'Meta Platforms, Inc.',
    date: '2024-02-23',
  },
  {
    id: 17,
    status: 'Interview',
    image: 'https://logo.clearbit.com/zoom.us',
    role: 'Software Engineer',
    companyName: 'Zoom Video Communications',
    date: '2024-02-21',
  },
  {
    id: 18,
    status: 'Wishlist',
    image: 'https://logo.clearbit.com/twitter.com',
    role: 'Full-Stack Developer',
    companyName: 'Twitter, Inc.',
    date: '2024-03-03',
  },
  {
    id: 19,
    status: 'Applied',
    image: 'https://logo.clearbit.com/coinbase.com',
    role: 'Full-Stack Developer',
    companyName: 'Coinbase, Inc.',
    date: '2024-02-18',
  },
  {
    id: 20,
    status: 'Interview',
    image: 'https://logo.clearbit.com/linkedin.com',
    role: 'Software Engineer',
    companyName: 'LinkedIn Corporation',
    date: '2024-02-26',
  },
];
