export const APPLICATIONS = [
  {
    id: 1,
    status: 'Wishlist',
    image: 'https://logo.clearbit.com/apple.com',
    role: 'Full-Stack Developer',
    companyName: 'Apple, Inc.',
    date: '2024/02/27',
  },
  {
    id: 2,
    status: 'Applied',
    image: 'https://logo.clearbit.com/nintendo.com',
    role: 'Software Engineer',
    companyName: 'Nintendo, Inc.',
    date: '2024/01/17',
  },
  {
    id: 3,
    status: 'Interview',
    image: 'https://logo.clearbit.com/nos.pt',
    role: 'UX Designer',
    companyName: 'NOS',
    date: '2024/02/22',
  },
  {
    id: 4,
    status: 'Wishlist',
    image: 'https://logo.clearbit.com/tesla.com',
    role: 'Product Manager',
    companyName: 'Tesla, Lda.',
    date: '2024/02/24',
  },
  {
    id: 5,
    status: 'Offer',
    image: 'https://logo.clearbit.com/microsoft.com',
    role: 'Data Scientist',
    companyName: 'Microsoft, Inc.',
    date: '2024/01/13',
  },
  {
    id: 6,
    status: 'Rejected',
    image: 'https://logo.clearbit.com/google.com',
    role: 'Marketing Manager',
    companyName: 'Google, Inc.',
    date: '2024/02/12',
  },
  {
    id: 7,
    status: 'Interview',
    image: 'https://logo.clearbit.com/ironhack.com',
    role: 'Business Analyst',
    companyName: 'Ironhack',
    date: '2024/02/10',
  },
  {
    id: 8,
    status: 'Wishlist',
    image: 'https://logo.clearbit.com/amazon.com',
    role: 'Software Developer',
    companyName: 'Amazon, Inc.',
    date: '2024/03/05',
  },
  {
    id: 9,
    status: 'Applied',
    image: 'https://logo.clearbit.com/spotify.com',
    role: 'UX Researcher',
    companyName: 'Spotify, Inc.',
    date: '2024/02/15',
  },
  {
    id: 10,
    status: 'Interview',
    image: 'https://logo.clearbit.com/airbnb.com',
    role: 'Product Designer',
    companyName: 'Airbnb',
    date: '2024/02/20',
  },
];
